### PR TITLE
more fixes for python3

### PR DESCRIPTION
**Pull request by fawaf**
in addition to some changes from @rfw

### CODE REVIEW

**Comment by gnowxilef** [comment]
poke?

**Comment by gnowxilef** [comment]
poketh

**Comment by gnowxilef** [comment]
poke

**Comment by pteichman** [comment]
I've integrated these into master and they'll be in cobe 3.0.1. I'd like to understand the motivation for the SQLite kwargs change a little more: I consider SQLite an implementation detail and would rather not leak that to the consumer if possible. Thanks!

**Pull request closed without merging**
